### ISSUE TITLE
Speed up / better image generation

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-devtools#10]
We could switch fake image generation to use [this package](https://www.npmjs.com/package/random-puppy) or [this one](https://www.npmjs.com/package/random-cat) and FileRecord.fromUrl(), which might be faster than dealing with buffers.

**Comment by aldeed** [comment]
In the new package, `FileRecord.fromUrl()` will fetch, transform, and store from that URL. If it's slower, then maybe not worth it. Just a thought.

**Comment by aldeed** [comment]
https://github.com/reactioncommerce/reaction-file-collections#store-a-file-from-a-remote-url

**Comment by zenweasel** [comment]
If it was even roughly equivalent I might do it just because those "static" images are hard on the eyes

**Comment by zenweasel** [comment]
Made this change in this PR: https://github.com/reactioncommerce/reaction-devtools/pull/14

**Comment by zenweasel** [comment]
So trying this out, this method is significantly slower (very roughly 5X) than the random image generation though this might vary depending on your internet speed. I am closing this issue for now as I have added the "Puppy" attachment option in the panel if people want to use that, which is helpful when doing functional testing since you can distinguish which image is which.
